### PR TITLE
Build BirchEngine with CMake

### PR DESCRIPTION
**Pull request by ssrobins**
Using modern CMake, I've made the following changes to how BirchEngine builds and deploys:

- It can build on Windows, Linux, and Mac and does some of the work in getting it working on Android and iOS
- It downloads and builds the SDL2, SDL2_image, png, and zlib libraries.  This keeps third-party source and binaries out of the source tree and provides automated builds of the libraries which makes upgrades quick and easy.
- All third-party libs are statically linked, including the runtime libs so deployment only requires copying the game executable and the assets folder to the computer.

I'd be happy to do a guest video or help you prepare one of your videos to show how to use this on Windows, Linux, and Mac, if you like.

I really like your Let's Make Games YouTube series.  Incrementally working through the process of adding features makes it very accessible.  Using free tools and open source libraries really puts the investment in trying to make a game as close to zero dollars as possible.  The use of modern C++ is a nice bonus!  Thanks!

-Steve

### CODE REVIEW

**Comment by hammackj** [comment]
Looks like SDL_ttf is missing. It is used in the asset manager.

**Comment by ssrobins** [comment]
Hi Jacob,

I wasn't routinely updating my fork after each new tutorial came out so it was missing some changes, including AssetManager.  I've synced my fork to master and added the CMake code for SDL_ttf and freetype.  I only verified it built and ran on Windows before pushing so let me know if you run into problems on other platforms.

**Comment by hammackj** [comment]
Thanks. I got it to compile on osx with some other minor changes. Wonder if the project is dead though? =\

**Comment by ssrobins** [comment]
Hope not, I really enjoy it.  Carl has done a lot to make it easier to get started with SDL2 and I really respect the work he's done!

Happy coding.

**Comment by ssrobins** [comment]
Thanks in part to this tutorial, I create a game! It's here:
https://github.com/ssrobins/stackblox 

It contains a CMake build system along with Conan for package management so all the goodies of this pull request and more are there for the taking. Closing this.

**Pull request closed without merging**
